### ISSUE TITLE
Non-Functioning on Amazon Tablet

### ISSUE THREAD

**Issue by rjm831** [ahmar20/com.aa.tvshows#2]
Installed app on a 7th gen Fire HD-10 (stock); app won't open.

**Comment by ahmar20** [comment]
I think it could be related to the Android ABI incompatibility. My app only supports `armeabi-v7a` and `arm64-v8a` at the moment. I have not yet enabled `x86` and `x86_64`. Is it possible that your tablet supports only x86* versions?

I don't have your tablet to test my app. If you can confirm what ABI your tablet uses then I can possibly provide a fix for this issue.

**Comment by rjm831** [comment]
14.01.2020, 10:39, "Ahmar" <notifications@github.com>:I think it could be related to the Android ABI incompatibility. My app only supports armeabi-v7a and arm64-v8a at the moment. I have not yet enabled x86 and x86_64. Is it possible that your tablet supports only x86* versions?
I don't have your tablet to test my app. If you can confirm what ABI your tablet uses then I can possibly provide a fix for this issue.

**Comment by ahmar20** [comment]
As it appears, the crash on startup is actually happening for almost everyone I think. This is because of inconsistency with ProGuard or d8. The layout files were unable to open and that caused the app to crash because no layout files were available. I have tested and app is working fine at the moment with release apk. I am going to push a new build with this fix today after I check everything.
